# Generated by Django 4.1.7 on 2023-10-13 22:18

import django.core.validators
from django.db import migrations, models
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_producto_imagen_producto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='image',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), inventario.models.validate_image_size]),
        ),
    ]
