# Generated by Django 4.1.7 on 2023-10-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_producto_precio_mayorista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='habilitar_caja',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades_por_caja',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
    ]
