# Generated by Django 4.1.7 on 2023-10-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_producto_habilitar_caja_producto_unidades_por_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidades_por_caja',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=25, null=True),
        ),
    ]
