# Generated by Django 4.1.7 on 2023-10-14 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_configuracion_v001'),
        ('inventario', '0010_alter_producto_habilitar_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Proveedor',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.proveedor'),
        ),
    ]
