# Generated by Django 4.1.7 on 2023-10-14 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_producto_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_unitario',
        ),
    ]
