# Generated by Django 4.1.7 on 2023-10-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_remove_producto_precio_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_mayorista',
        ),
    ]
