# Generated by Django 4.1.7 on 2023-10-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_configuracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion',
            old_name='ganancia_unitaria',
            new_name='ganancia_mayorista',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='ganancia_minorista',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
