# Generated by Django 4.1.7 on 2023-10-15 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contaduria', '0008_alter_asientocontable_options'),
        ('administracion', '0008_mediodepago_mediodecompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriagasto',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contaduria.cuentascontables'),
        ),
    ]
