# Generated by Django 4.1.7 on 2023-10-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_categoriagasto_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDeCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
