# Generated by Django 4.1.7 on 2023-10-16 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_familia'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.categoria'),
        ),
    ]
