# Generated by Django 4.1.7 on 2023-10-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_familia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='empresa',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
