# Generated by Django 4.1.7 on 2023-10-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_configuracion_ganancia_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='venta_por_caja',
            field=models.BooleanField(default=True),
        ),
    ]
