# Generated by Django 4.1.7 on 2023-10-17 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_de_egreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_de_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
