# Generated by Django 4.1.7 on 2023-11-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_costo_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Precio Venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Costo en Dolares'),
        ),
    ]
