# Generated by Django 4.1.7 on 2023-11-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_producto_precio_alter_producto_precio_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Costo en Dolares'),
        ),
    ]
