# Generated by Django 4.1.7 on 2023-11-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.CharField(max_length=120)),
                ('NombreApellido', models.CharField(max_length=120)),
                ('Direccion', models.CharField(blank=True, max_length=120, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Telefono', models.CharField(max_length=120)),
                ('UltimaModificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('Usuario', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
