# Generated by Django 4.1.7 on 2023-11-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='medioDeCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'medio de compra',
                'verbose_name_plural': 'Medios de compra',
            },
        ),
        migrations.CreateModel(
            name='medioDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'medio de pago',
                'verbose_name_plural': 'Medios de pago',
            },
        ),
    ]
