# Generated by Django 4.1.7 on 2023-11-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_mediodecompra_mediodepago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediodecompra',
            options={'verbose_name': 'medio de pago', 'verbose_name_plural': 'Medios de compra'},
        ),
        migrations.AlterModelOptions(
            name='mediodepago',
            options={'verbose_name': 'medio de pago', 'verbose_name_plural': 'Medios de venta'},
        ),
    ]
