# Generated by Django 4.1.7 on 2023-10-16 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_configuracion_venta_por_caja'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'verbose_name': 'detalle de venta', 'verbose_name_plural': 'Ventas por producto'},
        ),
        migrations.RenameField(
            model_name='detalleventa',
            old_name='precio',
            new_name='descuento',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='medio_de_pago',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta_por_caja',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.cliente'),
        ),
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Cuenta Corriente', 'Cuenta Corriente'), ('Redondeo', 'Redondeo')], default='Efectivo', max_length=25)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.mediodepago')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
        ),
    ]
