# Generated by Django 4.1.7 on 2023-10-18 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_detalleventa_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediodepago',
            name='medio',
        ),
    ]
