# Generated by Django 4.1.7 on 2023-10-18 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_configuracion_venta_por_caja'),
        ('ventas', '0003_remove_mediodepago_medio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediodepago',
            name='cuenta',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.mediodepago'),
        ),
    ]
