# Generated by Django 4.1.7 on 2023-10-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_mediodepago_cuenta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediodepago',
            options={'verbose_name': 'pago de cliente', 'verbose_name_plural': 'Pagos de clientes'},
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
