# Generated by Django 4.1.7 on 2023-10-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_mediodepago_options_venta_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediodepago',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
    ]
