# Generated by Django 4.1.7 on 2023-10-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_mediodepago_importe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediodepago',
            name='importe',
        ),
    ]
