# Generated by Django 4.1.7 on 2023-10-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaduria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentascontables',
            name='numero_de_cuenta',
            field=models.IntegerField(default=24, max_length=15),
            preserve_default=False,
        ),
    ]
