# Generated by Django 4.1.7 on 2023-10-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaduria', '0004_alter_cuentascontables_numero_de_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientos',
            name='descripcion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asientos',
            name='iibb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name='asientos',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name='asientos',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
    ]
