# Generated by Django 4.1.7 on 2023-10-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaduria', '0005_asientos_descripcion_asientos_iibb_asientos_importe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadosContables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_cuenta', models.IntegerField(unique=True)),
                ('tipo', models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('PASIVO', 'PASIVO'), ('PATRIMONIO NETO', 'PATRIMONIO NETO'), ('INGRESOS', 'INGRESOS'), ('COSTOS DE VENTAS', 'COSTOS DE VENTAS'), ('GASTOS OPERATIVOS', 'GASTOS OPERATIVOS'), ('OTROS INGRESOS', 'OTROS INGRESOS'), ('OTROS GASTOS', 'OTROS GASTOS'), ('RETIROS DE EFECTIVO', 'RETIROS DE EFECTIVO')], default=1, max_length=255, null=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='cuentascontables',
            old_name='numero_de_cuenta',
            new_name='cuenta',
        ),
        migrations.AddField(
            model_name='cuentascontables',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cuentascontables',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('PASIVO', 'PASIVO'), ('PATRIMONIO NETO', 'PATRIMONIO NETO'), ('INGRESOS', 'INGRESOS'), ('COSTOS DE VENTAS', 'COSTOS DE VENTAS'), ('GASTOS OPERATIVOS', 'GASTOS OPERATIVOS'), ('OTROS INGRESOS', 'OTROS INGRESOS'), ('OTROS GASTOS', 'OTROS GASTOS'), ('RETIROS DE EFECTIVO', 'RETIROS DE EFECTIVO')], default=1, max_length=255, null=True),
        ),
    ]
