# Generated by Django 4.1.7 on 2023-10-15 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contaduria', '0006_estadoscontables_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=25)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=25)),
                ('iibb', models.DecimalField(decimal_places=2, max_digits=25)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contaduria.cuentascontables')),
            ],
        ),
        migrations.RemoveField(
            model_name='asientos',
            name='cuenta',
        ),
        migrations.DeleteModel(
            name='estadosContables',
        ),
        migrations.DeleteModel(
            name='asientos',
        ),
    ]
