# Generated by Django 4.1.7 on 2023-10-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contaduria', '0007_asientocontable_remove_asientos_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asientocontable',
            options={'verbose_name': 'asiento contable', 'verbose_name_plural': 'Libro mayor'},
        ),
    ]
