# Generated by Django 4.1.7 on 2023-10-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reporteVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('ventas', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('total_minorista', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('total_mayorista', models.DecimalField(decimal_places=2, default=1, max_digits=25)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('total_iibb', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
            ],
        ),
    ]
