# Generated by Django 4.1.7 on 2023-10-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_reporteventas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteventas',
            name='total_mayorista',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
    ]
