# Generated by Django 4.1.7 on 2023-10-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_reporteventas_total_mayorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='reporteImpositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ventas', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('total_iibb', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='reporteventas',
            name='total_iibb',
        ),
        migrations.RemoveField(
            model_name='reporteventas',
            name='total_iva',
        ),
    ]
