# Generated by Django 4.1.7 on 2023-10-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_reporteimpositivo_remove_reporteventas_total_iibb_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reporteImpositivo',
        ),
        migrations.AddField(
            model_name='reporteventas',
            name='total_iibb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name='reporteventas',
            name='total_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
    ]
