# Generated by Django 4.1.7 on 2023-10-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_delete_reporteimpositivo_reporteventas_total_iibb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporteventas',
            old_name='total_iva',
            new_name='total_iva_10_5',
        ),
        migrations.AddField(
            model_name='reporteventas',
            name='total_iva_21',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
    ]
