# Generated by Django 4.1.7 on 2023-10-26 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=25)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=25)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
