# Generated by Django 4.1.7 on 2023-11-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_compraproducto_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='producto',
        ),
    ]
