# Generated by Django 4.1.7 on 2023-11-08 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_proveedor'),
        ('compra', '0004_remove_compra_cantidad_remove_compra_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.proveedor'),
        ),
    ]
