# Generated by Django 4.1.7 on 2023-11-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_mediodecompra_mediodepago'),
        ('compra', '0005_compra_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='medioDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.compra')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.mediodecompra', verbose_name='medio de pago')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'Pagos por compras',
            },
        ),
    ]
