# Generated by Django 4.1.7 on 2023-10-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_medio_de_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
