# Generated by Django 4.1.7 on 2023-10-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_detallecompra_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=25),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
    ]
