# Generated by Django 4.1.7 on 2023-10-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_detallecompra_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='medio_de_pago_2',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Cuenta Corriente', 'Cuenta Corriente')], default='Efectivo', max_length=25),
        ),
        migrations.AddField(
            model_name='compra',
            name='medio_de_pago_3',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Cuenta Corriente', 'Cuenta Corriente')], default='Efectivo', max_length=25),
        ),
    ]
