# Generated by Django 4.1.7 on 2023-10-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_compra_total_pagado_2_compra_total_pagado_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='medio_de_pago',
            new_name='medio_de_pago_1',
        ),
    ]
