# Generated by Django 4.1.7 on 2023-10-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_rename_medio_de_pago_compra_medio_de_pago_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Cuenta Corriente', 'Cuenta Corriente')], default='Efectivo', max_length=25)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compra')),
            ],
        ),
    ]
