# Generated by Django 4.1.7 on 2023-10-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_mediodepago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='medio_de_pago_1',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='medio_de_pago_2',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='medio_de_pago_3',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='total_pagado_1',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='total_pagado_2',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='total_pagado_3',
        ),
    ]
