# Generated by Django 4.1.7 on 2023-10-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_alter_mediodepago_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
    ]
