# Generated by Django 4.1.7 on 2023-10-15 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_detallecompra_descuento_detallecompra_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediodepago',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compra'),
        ),
    ]
