# Generated by Django 4.1.7 on 2023-10-15 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_mediodepago_mediodecompra'),
        ('compras', '0013_alter_mediodepago_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediodepago',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.mediodecompra'),
        ),
    ]
