# Generated by Django 4.1.7 on 2023-10-18 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_mediodepago_cuenta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallecompra',
            options={'verbose_name': 'detalle de comrpa', 'verbose_name_plural': 'Compras por porducto'},
        ),
    ]
